name: Auto-approve and merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_approve_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Dependabot bump
        id: dependabot_bump
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q ".*dependabot.*"; then
            echo "::set-output name=bump::true"
          else
            echo "::set-output name=bump::false"
          fi

      - name: Auto-approve and merge pull request
        if: github.event.pull_request.title =~ /bump/i && steps.dependabot_bump.outputs.bump == 'true'
        uses: peter-evans/auto-approve-merge@v1
        with:
          github-token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          pull-request-number: ${{ github.event.number }}
